# Generated by Django 5.0.2 on 2024-02-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phoneno',
            field=models.IntegerField(),
        ),
    ]
